[workspace]
members = [
    "src/crates/infrastructure",
    "src/crates/domain",
    "src/crates/command",
    "src/crates/query",
]
[package]
name = "app"
version = "0.1.0-rc.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
anyhow.workspace = true
axum = { version = "0.7.9", features = ["macros"] }
dotenv = "0.15.0"
serde.workspace = true
serde_json = "1.0.133"
sqlx.workspace = true
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "std",
    "env-filter",
    "fmt",
] }
domain = { path = "./src/crates/domain" }
infrastructure = { path = "./src/crates/infrastructure" }
command = { path = "./src/crates/command" }

[workspace.dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
mockall = "0.13.1"
tokio = { version = "1.42.0", features = ["full"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio-native-tls"] }

[dev-dependencies]
tower = { version = "0.5.2", features = ["util"] }
