services:
  zookeeper:
    image: debezium/zookeeper:2.5
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:2.5
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
    image: debezium/connect:2.5
    ports:
      - 8083:8083
    links:
      - kafka
      - db
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    volumes:
      - ./debezium:/debezium
    command: >
      /bin/bash -c "
        sh /debezium/register-debezium-connector.sh &
        /docker-entrypoint.sh start
      "
  server:
    build:
      context: ./Docker/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      - db
      - redis
  db:
    build:
      context: ./Docker/db
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - ./Docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    build:
      context: ./Docker/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
