[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono = "0.4.38"
mockall.workspace = true
rand = "0.8.4"

[dev-dependencies]
anyhow = { workspace = true }

[features]
test-utils = []
