[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
mockall.workspace = true
domain = { path = "../domain" }
tokio.workspace = true
